# Generated by Django 3.2.7 on 2021-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20210928_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_slug',
            field=models.SlugField(default='movie', max_length=60, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='seance_slug',
            field=models.SlugField(default='seance', max_length=60, verbose_name='Ссылка'),
        ),
    ]
