# Generated by Django 3.2.7 on 2021-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210928_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ManyToManyField(null=True, to='cms.Ticket', verbose_name='Билет'),
        ),
    ]
