# Generated by Django 3.2.7 on 2021-09-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210929_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ticket', verbose_name='Билет'),
        ),
    ]
