# Generated by Django 3.2.7 on 2022-12-28 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='seance_slug',
            field=models.SlugField(max_length=60, verbose_name='Ссылка'),
        ),
    ]
